### ISSUE TITLE
How to do a match with small step in cpymad?

### ISSUE THREAD

**Issue by cpyman** [hibtc/cpymad#21]
Hi, Thomas
When I match a sequence with small step, i.e. 1e-6, an error occurs.

python script:HITFIL.py
```python
# -*- coding: utf-8 -*-
"""
Created on Wed Jun 24 16:10:50 2015

@author: Administrator
"""


from cpymad.madx import Madx

m = Madx(command_log='MATCH1.log')
print (m.version)

m.call('../MATCH1.madx')
m.survey(sequence='FODO')

m.match(
  constraints=[
    dict(range='#e', MUX='0.16', MUY='0.25')
    ],
    vary=['QF->K1', 'QD->k1']
    )
```

madx file: MATCH1.madx
```
TITLE,'Example 3: MATCH1.MADX';
BEAM, PARTICLE = ELECTRON, PC = 3.0;

D: DRIFT, L = 1.0;
QF: QUADRUPOLE, L = 0.5, K1 := 0.2;
QD: QUADRUPOLE, L = 0.5, K1 := -0.2;

FODO: LINE = (QF, 5*(D), QD, QD, 5*(D), QF);
USE, PERIOD = FODO;
```

error information:
```python
runfile('E:/cython_madx/test/cpymad/3.py', wdir='E:/cython_madx/test/cpymad')
MAD-X 5.02.05 (2015.04.06)
Traceback (most recent call last):

  File "<ipython-input-14-9bd326b5c062>", line 1, in <module>
    runfile('E:/cython_madx/test/cpymad/3.py', wdir='E:/cython_madx/test/cpymad')

  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 601, in runfile
    execfile(filename, namespace)

  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 66, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "E:/cython_madx/test/cpymad/3.py", line 21, in <module>
    vary=['QF->K1', 'QD->k1']

  File "C:\Python27\lib\site-packages\cpymad-0.10.6-py2.7-win32.egg\cpymad\madx.py", line 424, in match
    sequence = self._use(sequence)

  File "C:\Python27\lib\site-packages\cpymad-0.10.6-py2.7-win32.egg\cpymad\madx.py", line 388, in _use
    or not self._libmadx.is_sequence_expanded(sequence)):

  File "C:\Python27\lib\site-packages\cpymad-0.10.6-py2.7-win32.egg\cpymad\_rpc.py", line 93, in DeferredMethod
    funcname, args, kwargs)

  File "C:\Python27\lib\site-packages\cpymad-0.10.6-py2.7-win32.egg\cpymad\rpc_util\client.py", line 80, in _request
    self._conn.send((kind, args))

  File "C:\Python27\lib\site-packages\cpymad-0.10.6-py2.7-win32.egg\cpymad\rpc_util\connection.py", line 53, in send
    return pickle.dump(data, self._send, -1)

  File "C:\Python27\lib\site-packages\cpymad-0.10.6-py2.7-win32.egg\cpymad\_rpc.py", line 93, in DeferredMethod
    funcname, args, kwargs)

  File "C:\Python27\lib\site-packages\cpymad-0.10.6-py2.7-win32.egg\cpymad\rpc_util\client.py", line 91, in _request
    return self._dispatch(response)

  File "C:\Python27\lib\site-packages\cpymad-0.10.6-py2.7-win32.egg\cpymad\rpc_util\client.py", line 97, in _dispatch
    return handler(*args)

  File "C:\Python27\lib\site-packages\cpymad-0.10.6-py2.7-win32.egg\cpymad\rpc_util\client.py", line 101, in _dispatch_exception
    raise exc_info

AttributeError: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\cpymad-0.10.6-py2.7-win32.egg\cpymad\rpc_util\service.py", line 85, in _dispatch
    response = handler(*args)
  File "C:\Python27\lib\site-packages\cpymad-0.10.6-py2.7-win32.egg\cpymad\_rpc.py", line 110, in _dispatch_function_call
AttributeError: 'module' object has no attribute '__getnewargs__'
```

**Comment by coldfix** [comment]
OK. Better. There is a small bug in cpymad which causes this particular error message. I have fixed it and uploaded a patch. You can either:
- check out the new master branch and go through the installation process.
- specify the sequence name explicitly when matching (which you should probably do anyway), i.e. `match('FODO', ...)`

There is some additional problem with your code that will happen once you get rid of the current error. I believe you will be able to figure it out on your own (look at the command log file).

**Comment by cpyman** [comment]
Yes, there indeed exists an error with my code. Sorry, I can find the error you mentioned.
```pattern='full'``` in the command log file?

**Comment by coldfix** [comment]
Try to run the command log directly from madx, the same error will occur. Why?

**Comment by cpyman** [comment]
Aha, MUY should be a numeric not a string.OK?

**Comment by cpyman** [comment]
Hi, how to control the precision of match processof a step, i.e. 1e-6?

**Comment by cpyman** [comment]
Sorry, this must a madx error not cpymad.

**Comment by coldfix** [comment]
Correct: Numbers are not strings.

About controlling vary step:

I could give you the answer, but I think you will learn much more from trying to figure it out on your own. This is a good opportunity for you to just start reading the cpymad source code. cpymad is not a lot of code and mostly just simple python. And you don't even need to look at everything. Most of the time its sufficient to look at small code sections. In particular, the `Madx.match` function is quite small and it won't take you much time to see what it can and can't do currently.

You will see, that for small code bases such as cpymad, you will in general be faster reading the corresponding source on your own than asking other persons (and it won't take their time too!). And the best part about it: you will be able to fix what you need fixed or add what you need added on your own.

Also, remember [my last post on this matter](https://github.com/hibtc/cpymad/issues/17#issuecomment-113491391).

May I ask, how old are you?

**Comment by cpyman** [comment]
27
I am a first year PHD.

What about you?

**Comment by cpyman** [comment]
In fact, I have read Cpymad source code once, but, have never understood it completely.

**Comment by coldfix** [comment]
I'm 27 too;), but still doing my master thesis in information theory (did lots of extra courses + working part time thats why I'm a bit late).

Well, its always hard to dive into new things, and trying to understand all of it at once is probably too much. But just keep on trying to understand the gist, and you will probably pick up a thing or two about python on the way too. And being able to modify the source according to your needs will be worth the effort! (cpymad is not a *finished* software - I'm just adding things when I need them for my work at HIT)

**Comment by cpyman** [comment]
Yes, that's all right.
Indeed, to dive into a new thing is a pain way especially into a quite different fields.
Thans a lot for your kind help.
If having problem I will still ask help from you, but with a minimal example.
Best regards!
