### ISSUE TITLE
How to use survey in cpymad?

### ISSUE THREAD

**Issue by cpyman** [hibtc/cpymad#24]
Hi,

How to get a survey table using ```survey``` command?

When I run 
```python 
survey = madx.survey(sequence='myring',columns=['s','l','angle'])
```
an error occurs.

However, when running ,
```python 
survey = madx.command.survey(sequence='myring',columns=['s','l','angle'])
```
no error occurs, but I can't find anything about survey in variable explorer.

Error displaces.
```python
survey = madx.survey(sequence='myring',columns=['s','l','angle'])

Traceback (most recent call last):

  File "<ipython-input-84-7e6faf6b7761>", line 1, in <module>
    survey = madx.survey(sequence='myring',columns=['s','l','angle'])

  File "C:\Python27\lib\site-packages\cpymad-0.10.6-py2.7-win32.egg\cpymad\madx.py", line 358, in survey
    return self.get_table('survey', columns)

  File "C:\Python27\lib\site-packages\cpymad-0.10.6-py2.7-win32.egg\cpymad\madx.py", line 460, in get_table
    return proxy.copy(columns)

  File "C:\Python27\lib\site-packages\cpymad-0.10.6-py2.7-win32.egg\cpymad\madx.py", line 744, in copy
    table.summary = self.summary

  File "C:\Python27\lib\site-packages\cpymad-0.10.6-py2.7-win32.egg\cpymad\madx.py", line 730, in summary
    return self._libmadx.get_table_summary(self._name)

  File "C:\Python27\lib\site-packages\cpymad-0.10.6-py2.7-win32.egg\cpymad\_rpc.py", line 93, in DeferredMethod
    funcname, args, kwargs)

  File "C:\Python27\lib\site-packages\cpymad-0.10.6-py2.7-win32.egg\cpymad\rpc_util\client.py", line 91, in _request
    return self._dispatch(response)

  File "C:\Python27\lib\site-packages\cpymad-0.10.6-py2.7-win32.egg\cpymad\rpc_util\client.py", line 97, in _dispatch
    return handler(*args)

  File "C:\Python27\lib\site-packages\cpymad-0.10.6-py2.7-win32.egg\cpymad\rpc_util\client.py", line 101, in _dispatch_exception
    raise exc_info

ValueError: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\cpymad-0.10.6-py2.7-win32.egg\cpymad\rpc_util\service.py", line 85, in _dispatch
    response = handler(*args)
  File "C:\Python27\lib\site-packages\cpymad-0.10.6-py2.7-win32.egg\cpymad\_rpc.py", line 111, in _dispatch_function_call
  File "cpymad\libmadx.pyx", line 277, in cpymad.libmadx.get_table_summary (cpymad/libmadx.c:2703)
    raise ValueError("No summary for table: {!r}".format(table_name))
ValueError: No summary for table: 'survey'
```

**Comment by coldfix** [comment]
Please give a minimal example + MAD-X output.

**Comment by cpyman** [comment]
Hi, Thomas

I think I have solved this problem with a verbose way.

I just add ```file='1'``` in survey command, and then survey prints result to a file with name '1'. But,  I don't know if there exists another way to solve this.

my code is at below.
```python
from cpymad.madx import Madx
madx = Madx(command_log="HIMM_log.madx")
madx.command.call(file="HIMM.txt")
survey = madx.command.survey(sequence='myring',file='1')
with open('1') as survey1:
    f = survey1.readlines()
```

**Comment by coldfix** [comment]
Ok, closing this, since you didn't provide a full minimal example and seem to be fine with your solution.
