### ISSUE TITLE
ValueError: No summary for table: 'twiss'

### ISSUE THREAD

**Issue by cpyman** [hibtc/cpymad#27]
Hi, Thomas

I have a question to ask for your help again. 
When I run the  syntax ```twiss = madx.twiss(sequence='myline',columns=['s','x','y','betx','bety','Dx','Dy'])```， an error occurs. But, while running in plain madx, there have no any errors.

error information:
```python
runfile('E:/HIMM_commissioning/cpymad/mebt.py', wdir='E:/HIMM_commissioning/cpymad')
MAD-X 5.02.05 (2015.04.06)
Traceback (most recent call last):

  File "<ipython-input-7-40ce0ada60f3>", line 1, in <module>
    runfile('E:/HIMM_commissioning/cpymad/mebt.py', wdir='E:/HIMM_commissioning/cpymad')

  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 601, in runfile
    execfile(filename, namespace)

  File "C:\Python27\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 66, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "E:/HIMM_commissioning/cpymad/mebt.py", line 18, in <module>
    twiss = madx.twiss(sequence='myline',columns=['s','x','y','betx','bety','Dx','Dy'])

  File "C:\Python27\lib\site-packages\cpymad-0.10.6-py2.7-win32.egg\cpymad\madx.py", line 340, in twiss
    return self.get_table('twiss', columns)

  File "C:\Python27\lib\site-packages\cpymad-0.10.6-py2.7-win32.egg\cpymad\madx.py", line 460, in get_table
    return proxy.copy(columns)

  File "C:\Python27\lib\site-packages\cpymad-0.10.6-py2.7-win32.egg\cpymad\madx.py", line 744, in copy
    table.summary = self.summary

  File "C:\Python27\lib\site-packages\cpymad-0.10.6-py2.7-win32.egg\cpymad\madx.py", line 730, in summary
    return self._libmadx.get_table_summary(self._name)

  File "C:\Python27\lib\site-packages\cpymad-0.10.6-py2.7-win32.egg\cpymad\_rpc.py", line 93, in DeferredMethod
    funcname, args, kwargs)

  File "C:\Python27\lib\site-packages\cpymad-0.10.6-py2.7-win32.egg\cpymad\rpc_util\client.py", line 91, in _request
    return self._dispatch(response)

  File "C:\Python27\lib\site-packages\cpymad-0.10.6-py2.7-win32.egg\cpymad\rpc_util\client.py", line 97, in _dispatch
    return handler(*args)

  File "C:\Python27\lib\site-packages\cpymad-0.10.6-py2.7-win32.egg\cpymad\rpc_util\client.py", line 101, in _dispatch_exception
    raise exc_info

ValueError: 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\cpymad-0.10.6-py2.7-win32.egg\cpymad\rpc_util\service.py", line 85, in _dispatch
    response = handler(*args)
  File "C:\Python27\lib\site-packages\cpymad-0.10.6-py2.7-win32.egg\cpymad\_rpc.py", line 111, in _dispatch_function_call
  File "cpymad\libmadx.pyx", line 277, in cpymad.libmadx.get_table_summary (cpymad/libmadx.c:2703)
    raise ValueError("No summary for table: {!r}".format(table_name))
ValueError: No summary for table: 'twiss'

```

python code:
```python
from cpymad.madx import Madx
madx = Madx(command_log="HIMM_log.madx")
print(madx.version)
madx.command.call(file="1.txt")
twiss = madx.twiss(sequence='myline',columns=['s','x','y','betx','bety','Dx','Dy'])
import matplotlib.pylab as plt
plt.plot(twiss['s'], twiss['betx'])
```

madx file with name '1.txt':
```
TITLE ,"mebt";
BEAM, PARTICLE=proton, PC=1.69602771203775;

D1: DRIFT, L=1;
Q1: QUADRUPOLE, L=0.35, K1=-3.6013728752;
D2: DRIFT, L=0.35;
Q2: QUADRUPOLE, L=0.35, K1=4.3532656572;
D3: DRIFT, L=0.35;
Q3: QUADRUPOLE, L=0.35, K1=-2.3119829633;
D4: DRIFT, L=4.2150399;
Q4: QUADRUPOLE, L=0.35, K1=-3.6602446906;
D5: DRIFT, L=0.5;
Q5: QUADRUPOLE, L=0.35, K1=3.4786544844;
D6: DRIFT, L=1;
B1: SBEND, L=0.43022366062, ANGLE=-0.43022366062, 
 K1=0, E1=-0.21511183031, E2=-0.21511183031, 
 K2=0, HGAP=0.035, FINT=0;
D7: DRIFT, L=1;
B2: SBEND, L=0.43022366062, ANGLE=-0.43022366062, 
 K1=0, E1=-0.21511183031, E2=-0.21511183031, 
 K2=0, HGAP=0.035, FINT=0;
D8: DRIFT, L=1;
Q6: QUADRUPOLE, L=0.4, K1=2.8872328397;
D9: DRIFT, L=1.5;
Q7: QUADRUPOLE, L=0.4, K1=-1.65754164;
D10: DRIFT, L=1.5;
Q8: QUADRUPOLE, L=0.4, K1=1.4539004262;
D11: DRIFT, L=1.5232458;
B3: SBEND, L=0.43022366062, ANGLE=-0.43022366062, 
 K1=0, E1=-0.21511183031, E2=-0.21511183031, 
 K2=0, HGAP=0.035, FINT=0;
D12: DRIFT, L=2.5;

myline: LINE=(D1,Q1,D2,Q2, 
                D3,Q3,D4,Q4, 
                D5,Q5,D6,B1, 
                D7,B2,D8,Q6, 
                D9,Q7,D10,Q8, 
                D11,B3,D12);
use,sequence=myline;
```

**Comment by cpyman** [comment]
Aha, I think I have solved this problem.
For transfer line, initial twiss values have to assigned， which differs from ring that have a period solution.
In python code I replaced ```twiss = madx.twiss(sequence='myline',columns=['s','x','y','betx','bety','Dx','Dy'])  ``` with ``` twiss = madx.twiss(sequence='myline',betx=10.89,alfx=-4.48,dx=1.77,dpx=0.66,bety=6.98,alfy=-12.4,dy=0,dpy=0) ```, so it works well.

**Comment by coldfix** [comment]
Hey,

glad to hear, you solved it on your own. So this can be closed now? (You can just close if your problem is fixed)
